[tool.poetry]
name = "test-python"
version = "0.1.0"
description = ""
authors = ["Evangelos Pappas <epappas@evalonlabs.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
